PUDGEWARS_VERSION = 7.20

PRE_GAME_TIME = 10.0
TREE_REGROW_TIME = 1.0
POST_GAME_TIME = 120.0

GOLD_PER_TICK = 25
GOLD_TICK_TIME = 10.0

MAX_LEVEL = 42

FIXED_RESPAWN_TIME = 7.0

STARTING_GOLD = 0

AUTO_LAUNCH_DELAY = 10.0
LOCK_TEAM_SETUP = true

-- Runes Variables
RUNE_SPAWN_TIME = 30.0
RUNE_TEXT_DURATION = 4.0
RUNE_SLOW = false
RUNE_SLOW_DURATION = 15.0
RUNE_SHIELD_DURATION = 12.0
RUNE_FIRE_DURATION = 24.0
